### ISSUE TITLE
可以提供隐藏超出最大最小时间范围的属性么

### ISSUE THREAD

**Issue by program-APE** [wuwuFQ/FQDateTimeSDK#4]
假设可选时间范围为 1990-01-01 ~ 2022-09-29
不希望1990-01-01之前和2022-09-29之后的日期可以滚动出来
可否提供参数隐藏范围外的时间展示
另外在以上假设范围的情况下,滚动到0-1-1时控件不会自动回滚到范围内的最小时间值

**Comment by wuwuFQ** [comment]
请更新版本

**Comment by wuwuFQ** [comment]
> 假设可选时间范围为 1990-01-01 ~ 2022-09-29 不希望1990-01-01之前和2022-09-29之后的日期可以滚动出来 可否提供参数隐藏范围外的时间展示 另外在以上假设范围的情况下,滚动到0-1-1时控件不会自动回滚到范围内的最小时间值


请更新版本

**Comment by wuwuFQ** [comment]
这个功能可以加上，请关注

**Comment by program-APE** [comment]
> 

感谢wuwu回复,期待此功能的添加.
更新方面,目前cocopods只能更新到1.0.5.
执行pod search 结果如下:
-> FQDateTimeSDK (1.0.5)
   iOS年月日时分秒选择器.
   pod 'FQDateTimeSDK', '~> 1.0.5'
   - Homepage: https://github.com/wuwuFQ/FQDateTimeSDK
   - Source:   https://github.com/wuwuFQ/FQDateTimeSDK.git
   - Versions: 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0, 0.0.1 [trunk repo]
(END)

**Comment by wuwuFQ** [comment]
> 

配置文件   pod 'FQDateTimeSDK',    不要指定版本
在终端执行  pod update FQDateTimeSDK

**Comment by program-APE** [comment]
> > 
> 
> 配置文件 pod 'FQDateTimeSDK', 不要指定版本 在终端执行 pod update FQDateTimeSDK

嗯 更新成功了 但是滚动到0-01-01后不自动回滚到可选范围内最小时间值的情况依然存在

**Comment by wuwuFQ** [comment]
> 

已更新到1.1版本，请更新后使用
