### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Czing** [wuwuFQ/FQDateTimeSDK#5]
有不少BUG 默认时间更换后 时间是错的，

**Comment by wuwuFQ** [comment]
首先    FQDateTimePickerView *pickerView = [[FQDateTimePickerView alloc] init];
你修改defaultDate 确认是操作的同一个pickerView对象吗？
你修改后在showPicker的时候，代码会判断你设置的默认时间是否在你给的时间范围内
