### ISSUE TITLE
Archive 时报错 Undefined symbol: _OBJC_CLASS_$_FQDateTimePickerView

### ISSUE THREAD

**Issue by program-APE** [wuwuFQ/FQDateTimeSDK#6]
通过 Cocopods 引用, 运行正常, 但是 Archive 时报错
Undefined symbol: _OBJC_CLASS_$_FQDateTimePickerView

Xcode Version 13.3.1 (13E500a)

**Comment by program-APE** [comment]
Target -> Build Setting -> Architectures 
$(ARCHS_STANDARD) 改成 arm64 可以打包成功

**Comment by wuwuFQ** [comment]
> 

目前Apple只支持arm64和x86_64，你在新的Xcode里面已经没有armv7等系统架构了
